### PR TITLE
Background updates (edit needed)

### PR DESCRIPTION
**Pull request by Hypertyrannical**
I don't really know where the comments above declaring the selector come from, could you let me in on that?

(I won't be offended if you close this PR and do your own commit.)

### CODE REVIEW

**Comment by IndyV** [comment]
Hi, Joe is currently working on [v2](https://github.com/joe27g/Discord-Theme/tree/v2) which should also fix issues with the theme. Please be patient

**Comment by Hypertyrannical** [comment]
@IndyV I'm _using_ v2, and this PR is pushing to v2

**Comment by IndyV** [comment]
I'm sorry I misread it. Thanks for your contribution

**Comment by joe27g** [comment]
For reference, the notation I'm using is for modules, such that the classes could be automatically updated by a script. For example, `(username:bot)` would be found at `findModule("username").bot`, which would resolve to `bot-2Fta1w`.

**Pull request merged**
